### ISSUE TITLE
Export to FDSN is raising an Exception

### ISSUE THREAD

**Issue by javiquinte** [EIDA/routing#85]
It is not clear what is causing this. The error in the logs is:

```
Jul 10 10:10:47 routingsvc1 uwsgi: Traceback (most recent call last):
Jul 10 10:10:47 routingsvc1 uwsgi:   File "/var/www/html/eidaws/routing/1/routing.py", line 435, in application
Jul 10 10:10:47 routingsvc1 uwsgi:     result = routes.globalConfig()
Jul 10 10:10:47 routingsvc1 uwsgi:   File "/var/www/html/eidaws/routing/1/routeutils/utils.py", line 1419, in globalConfig
Jul 10 10:10:47 routingsvc1 uwsgi:     result = self.getRoute(Stream('*', '*', '*', '*'), TW(None, None),
Jul 10 10:10:47 routingsvc1 uwsgi:   File "/var/www/html/eidaws/routing/1/routeutils/utils.py", line 1475, in getRoute
Jul 10 10:10:47 routingsvc1 uwsgi:     raise RoutingException('No routes found!')
Jul 10 10:10:47 routingsvc1 uwsgi: routeutils.utils.RoutingException: No routes found!
```
The error appear only some days. The fact that is not permanent gives an idea that this could be caused by malformed(?) routes. This needs to be debugged ASAP.

**Comment by javiquinte** [comment]
Fixed with commit fd5242683d4088cbdb3032e7e63779a10c037446
